services:

    app:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        image: jez500/pricebuddy:latest
        ports:
            - 8080:80
        volumes:
            - storage:/app/storage
        environment:
            DB_HOST: database
            DB_USERNAME: pricebuddy
            DB_PASSWORD: pric3buddy
            DB_DATABASE: pricebuddy
            APP_USER_EMAIL: admin@example.com
            APP_USER_PASSWORD: admin
            SCRAPER_BASE_URL: http://scraper:3000
        depends_on:
            - database
        networks:
            - default

    database:
        image: mysql:8.2
        environment:
            MYSQL_DATABASE: pricebuddy
            MYSQL_USER: pricebuddy
            MYSQL_PASSWORD: pric3buddy
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - database:/var/lib/mysql
        networks:
            - default

    scraper:
        image: amerkurev/scrapper:latest
        networks:
            - default
        ports:
            - 3030:3000 # Optional, if you want to access the scrapper api from the host machine

volumes:
    storage:
    database:

networks:
    default:
